### ISSUE TITLE
Missing email content/templates

### ISSUE THREAD

**Issue by mirgj** [Kong/kong-portal-templates#112]
The current version doesn't contain the default emails content / templates for reference.
As per docs the new version (1.3.0.1) has this feature: https://docs.konghq.com/enterprise/1.3-x/developer-portal/theme-customization/emails/ 

Kong Portal CLI already has email support: https://github.com/kong/kong-portal-cli

**Comment by nateslo** [comment]
Hi @mirgj. We will be merging the email templates as well as other updates from 1.3.0.1 into the master branch soon. If you would like to use them now, you can find them on the [dev-master](https://github.com/Kong/kong-portal-templates/tree/dev-master).

**Comment by nateslo** [comment]
Master has been updated with the latest from dev-master. Now contains email templates. https://github.com/Kong/kong-portal-templates/commit/b7978176935192a457213c6016e01c42cdc0de4f
