### ISSUE TITLE
Internationalize the reset-password page

### ISSUE THREAD

**Issue by jeromegervais** [Kong/kong-portal-templates#155]
Is there any way to internationalize the form in the reset-password page ?

It seems that the wording comes the dashboard-xxx.min.js file, and that it is not localized.

**Comment by Jlawlzz** [comment]
Hi  @jeromegervais, while we do not technically support changing the values out of the box yet, there is a workaround that can help you achieve the desired result.  Please check out the two files below from a demo branch I just pushed up:

[https://github.com/Kong/kong-portal-templates/blob/demo/localized-reset-password/workspaces/default/themes/base/layouts/reset-password.html](https://github.com/Kong/kong-portal-templates/blob/demo/localized-reset-password/workspaces/default/themes/base/layouts/reset-password.html)

[https://github.com/Kong/kong-portal-templates/blob/demo/localized-reset-password/workspaces/default/content/reset-password.txt
](https://github.com/Kong/kong-portal-templates/blob/demo/localized-reset-password/workspaces/default/content/reset-password.txt)

The changes above are:
1) Create a new layout outside of the `layouts/system` dir that is called `reset-password.html`.  This will replace the current layout that lives in `system`. This page removes the hardcoded values via CSS and replaces them with the dynamic ones included in the `reset-password.txt` content page.
2) Change the layout referenced by `reset-password.txt` to the new layout we just created.

**Comment by kinman** [comment]
@jeromegervais does @Jlawlzz's workaround meet your needs?

**Comment by jeromegervais** [comment]
Hi, sorry for the late answer.
In fact, mots of the wording comes from the dashboard-xxx.js file, that contains most of the logic.

So, some of the messages won't be translated.
But so be it :)

**Comment by Jlawlzz** [comment]
Hi @jeromegervais the workaround above should allow you to set your own text for the reset password page, the main limitation being that the text does not change once the submit button has been clicked.  That being said this type of approach only works on a small subset of the pages served from dashboard.min.js, pages like the `/dashboard` page is not customizable.  Let me know if you have any further questions!

<img width="1101" alt="Screen Shot 2020-06-22 at 9 24 56 AM" src="https://user-images.githubusercontent.com/11199673/85311650-9c4c4a80-b46a-11ea-882f-5baab3adb7bd.png">

**Comment by kinman** [comment]
With the approach above, only "Go Back to Login" is not localizable. We'll address this as part of a larger i18n effort in the future.
