### ISSUE TITLE
Why are the Frontend script & styles a mess?

### ISSUE THREAD

**Issue by pxwee5** [Kong/kong-portal-templates#174]
```
https://github.com/Kong/kong-portal-templates/blob/master/workspaces/default/themes/base/partials/auth/forms/login/basic-auth.html
```

and
```
assets/js/dashboard-6616db8.min.js
```

Why are you using both jQuery, inline javascript and Vue? 

Plus, some styles are in site.css, but some classes are embedded in Vue.

How do you go about editing the compiled Vue components? Such as the reset password component generated on runtime?

Is there a way to get the source for the vue components?

**Comment by HenriPro** [comment]
Hey @pxwee5 Sorry for the delayed response.

This repo is an amalgamation of templates meant to be user customizable as well as a Vue JS bundle not meant to be customized, and the spec loader which is plugin found here: at https://github.com/Kong/swagger-ui-kong-theme 
for Swagger-ui https://github.com/swagger-api/swagger-ui 

Styles in site.css are meant for customer customization, and ones in Vue are not. 

We hope the vue JS bundle as is meets your use case, if it does not please contact support. 

Thanks
