### ISSUE TITLE
directories & files not created in the case of a PULL

### ISSUE THREAD

**Issue by MosAmokhtari** [Kong/kong-portal-templates#68]
Before start with KONG please read the CONTRIBUTING.md guidelines to learn where and on which 
channel you can search for the help and can ask genral question

Also read the CODE_OF_CONDUCT.md to get the idea about code format and policies of KONG

 

### Summary

SUMMARY_GOES_HERE

Sync returns error as it cannot create the folders
### Steps To Reproduce

1. create a new workspace (myspace1) and enable DevPortal
2. create a folder in theme (same name myspace1) and run the command
3. WORKSPACE=myspace1 DIRECTORY=./themes/myspace1 PULL=true node bin/sync

### Additional Details & Logs
1 example of errors
pulling files from: http://localhost:8001/myspace2
File Created: ./themes/myspace1/partials/unauthenticated/search/widget-vue.hbs
Error: ENOENT: no such file or directory, open './themes/myspace1/partials/unauthenticated/search/widget-vue.hbs'
2. I thing the issue is with writeFilesSync function that does not create intermediate directories

I found this function that should do the job (Hope this help)

// like writeFileSync but creates all folder paths if not exist
// ----------------------------------------------------------
function writeFileSyncRecursive(filename, content, charset) {
	// create folder path if not exists
	filename.split('/').slice(0,-1).reduce( (last, folder)=>{
		let folderPath = last ? (last + '/' + folder) : folder
		if (!fs.existsSync(folderPath)) fs.mkdirSync(folderPath)
		return folderPath
	})
	
	fs.writeFileSync(filename, content, charset)
}

**Comment by rainest** [comment]
The legacy portal template release is probably unlikely to get newer versions, but sticking this in place does work with some modifications to library scope:

```
diff --git a/bin/sync.js b/bin/sync.js
index 6baa3c7..1e3f8ae 100755
--- a/bin/sync.js
+++ b/bin/sync.js
@@ -1,6 +1,6 @@
 #!/usr/bin/env node
 
-const {lstatSync, readdirSync, readFileSync, writeFileSync} = require('fs')
+const {existsSync, mkdirSync, lstatSync, readdirSync, readFileSync, writeFileSync} = require('fs')
 const {join, parse} = require('path').posix
 const readline = require('readline')
 const https = require('https')
@@ -80,6 +80,17 @@ if (process.argv[2] === '--curl' || process.argv[2] === '-c') {
   WATCH_DIR = false
 }
 
+function writeFileSyncRecursive(filename, content, charset) {
+       // create folder path if not exists
+       filename.split('/').slice(0,-1).reduce( (last, folder)=>{
+               let folderPath = last ? (last + '/' + folder) : folder
+               if (!existsSync(folderPath)) mkdirSync(folderPath)
+               return folderPath
+       })
+
+       writeFileSync(filename, content, charset)
+}
+
 function isEnvVarTrue (variable) {
   return variable ? variable.toLowerCase() === 'true' : false
 }
@@ -215,7 +226,7 @@ async function write () {
       }
 
       try {
-        writeFileSync(filePath, contents, {flag: 'w'})
+        writeFileSyncRecursive(filePath, contents, {flag: 'w'})
         return Promise.resolve()
       } catch (e) {
         console.log(e)
```
